spring.application.name=AuthenticationService
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/credentials
spring.datasource.username=root
spring.datasource.password=97979797
spring.jpa.show=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=18pa1a05d2@vishnu.edu.in
spring.mail.password=<password>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
